### ISSUE TITLE
是否考虑把【Stylesheet-让标题与按钮分隔开来】放到主题里面？

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/itonnote-theme#7]
```css
.tc-titlebar h2 {
	font-size: 1em;
	display: table-header-group;
	word-wrap:break-word;
	word-break:break-all;
}
.tc-tiddler-frame .tc-tiddler-controls {
	display: table-header-group;
	float: right;
	padding: 0px;
}
```

感觉这个效果还不错。

创建一个单独的条目存放。取名为Separate title and button

**Comment by linonetwo** [comment]
感觉可以，搞个开关吧

**Comment by linonetwo** [comment]
参考 https://github.com/tiddly-gittly/itonnote-theme/pull/6#issuecomment-1588478616

**Comment by Zacharia2** [comment]
```css
.tc-titlebar h2 {
	display: table-header-group;
	word-wrap:break-word;
	word-break:break-all;
}
```
发现仅有这段css代码是有用的。
